### ISSUE TITLE
UART not wroking

### ISSUE THREAD

**Issue by GoWest279** [parallella/parabuntu#23]
Hi, 
I'm running ubuntu 18.04 headless image on Parallela Desktop board. 
The SSH works fine, but the UART isn't. The setup is 115200bps, 8bit, no parity, 1 stop bit.
The output is as the attached image.
Did I miss anything of the setup? Thanks.
![image](https://user-images.githubusercontent.com/52974454/135778451-4326b5eb-4feb-4832-a7ee-7fd9247d5ead.png)

**Comment by tony-travis** [comment]
Which image are you booting?

**Comment by GoWest279** [comment]
> Which image are you booting?

Hi, Tony,
I'm using the **parabuntu-2019.1-beta1-headless-z7020.img.gz** with **linux4.14.0 kernel**. The ssh welcome message shows **Ubuntu 18.04.5 LTS**.
Thanks:)

**Comment by tony-travis** [comment]
On 05/10/2021 02:06, John Y. Liu wrote:
>     Which image are you booting?
> 
> Hi, Tony,
> I'm using the *parabuntu-2019.1-beta1-headless-z7020.img.gz* with 
> *linux4.14.0 kernel*. The ssh welcome message shows *Ubuntu 18.04.5 LTS*.
> Thanks:)

Hi, John.

I've booted that image on my Parallella and the UART i/o is working:

U-Boot 2012.10-00003-g792c31c (Jan 03 2014 - 12:24:08)

I2C:   ready
DRAM:  992 MiB
WARNING: Caches not enabled
MMC:   SDHCI: 0
SF: Detected N25Q128 with page size 64 KiB, total 16 MiB
In:    serial
Out:   serial
Err:   serial
Net:   zynq_gem
Hit any key to stop autoboot:  0
zynq-uboot> printenv
AdaptevaSKU=SKUP1601-01
baudrate=115200
bitstream_image=parallella.bit.bin
bootcmd=run modeboot
bootdelay=5
devicetree_image=devicetree.dtb
devicetree_size=0x20000
ethact=zynq_gem
ethaddr=04:4F:8B:00:29:EC
fdt_high=0x20000000
initrd_high=0x20000000
ipaddr=192.168.0.1
kernel_image=uImage
kernel_size=0x500000
modeboot=run qspiboot
qspiboot=echo Configuring PL and Booting Linux...;mmcinfo;fatload mmc 0 
0x4000000 ${bitstream_image};fpga load 0 0x4000000 0x3dbafc;fatload mmc 
0 0x3000000 ${kernel_image};fatload mmc 0 0x2A00000 
${devicetree_image};bootm 0x3000000 - 0x2A00000
serverip=192.168.0.1
stderr=serial
stdin=serial
stdout=serial

Environment size: 678/131068 bytes
zynq-uboot> boot
[...]
Ubuntu 18.04.3 LTS parallella ttyPS0

parallella login: parallella
Password:
Last login: Wed Sep 25 16:32:01 EDT 2019 on ttyPS0
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.14.0+ armv7l)

  * Documentation:  https://help.ubuntu.com
  * Management:     https://landscape.canonical.com
  * Support:        https://ubuntu.com/advantage

***@***.***:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
***@***.***:~$

HTH,

   Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        ***@***.***

**Comment by GoWest279** [comment]
I figured out it's my CP2102 USB-to-serial board is not functioning. I switched to a CH340G board, it's finally working:)
Thank you so much for your help!
