### ISSUE TITLE
No sound.

### ISSUE THREAD

**Issue by shodruky-rhyammer** [parallella/parabuntu#3]
Temporary solution:
$ sudo mkdir /dev/snd
$ sudo mknod -m 660 /dev/snd/controlC0 c 116 0
$ sudo mknod -m 660 /dev/snd/pcmC0D0p c 116 16
$ sudo mknod -m 660 /dev/snd/timer c 116 33
$ sudo chown root:audio /dev/snd/*

nano ~/.asoundrc
---- cut here ----
pcm.!default {
type rate
slave {
pcm "hw:0"
rate 48000
}
converter "samplerate"
}
---- cut here ----

**Comment by olajep** [comment]
Fixed in 2016.11. If you're using the HDMI images (and thus X11 / LXDE) you might want to edit `~/.asoundrc` to use pulseaudio as default for alsa applications (see instructions in the file).
